package com.briup.sports.mapper;

import com.briup.sports.bean.Addr;
import com.briup.sports.bean.AddrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    long countByExample(AddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int deleteByExample(AddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int deleteByPrimaryKey(Integer addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int insert(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int insertSelective(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    List<Addr> selectByExample(AddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    Addr selectByPrimaryKey(Integer addrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Addr record, @Param("example") AddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByExample(@Param("record") Addr record, @Param("example") AddrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByPrimaryKeySelective(Addr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByPrimaryKey(Addr record);
}