package com.briup.sports.mapper;

import com.briup.sports.bean.Qas;
import com.briup.sports.bean.QasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    long countByExample(QasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int deleteByExample(QasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int deleteByPrimaryKey(Integer ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int insert(Qas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int insertSelective(Qas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    List<Qas> selectByExample(QasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    Qas selectByPrimaryKey(Integer ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Qas record, @Param("example") QasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByExample(@Param("record") Qas record, @Param("example") QasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByPrimaryKeySelective(Qas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_qas
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByPrimaryKey(Qas record);
}