package com.briup.sports.mapper;

import com.briup.sports.bean.Weight;
import com.briup.sports.bean.WeightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    long countByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int deleteByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int deleteByPrimaryKey(String weightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int insert(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int insertSelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    List<Weight> selectByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    Weight selectByPrimaryKey(String weightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByExample(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByPrimaryKeySelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    int updateByPrimaryKey(Weight record);
}