package com.briup.sports.bean;

public class Addr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.addr_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer addrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.addr_province
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String addrProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.addr_city
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String addrCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.addr_county
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String addrCounty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.addr_detail
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String addrDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.member_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.member_tel
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_addr.addr_code
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer addrCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.addr_id
     *
     * @return the value of sys_addr.addr_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.addr_id
     *
     * @param addrId the value for sys_addr.addr_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.addr_province
     *
     * @return the value of sys_addr.addr_province
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getAddrProvince() {
        return addrProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.addr_province
     *
     * @param addrProvince the value for sys_addr.addr_province
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setAddrProvince(String addrProvince) {
        this.addrProvince = addrProvince == null ? null : addrProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.addr_city
     *
     * @return the value of sys_addr.addr_city
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getAddrCity() {
        return addrCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.addr_city
     *
     * @param addrCity the value for sys_addr.addr_city
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setAddrCity(String addrCity) {
        this.addrCity = addrCity == null ? null : addrCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.addr_county
     *
     * @return the value of sys_addr.addr_county
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getAddrCounty() {
        return addrCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.addr_county
     *
     * @param addrCounty the value for sys_addr.addr_county
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setAddrCounty(String addrCounty) {
        this.addrCounty = addrCounty == null ? null : addrCounty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.addr_detail
     *
     * @return the value of sys_addr.addr_detail
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getAddrDetail() {
        return addrDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.addr_detail
     *
     * @param addrDetail the value for sys_addr.addr_detail
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setAddrDetail(String addrDetail) {
        this.addrDetail = addrDetail == null ? null : addrDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.member_id
     *
     * @return the value of sys_addr.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.member_id
     *
     * @param memberId the value for sys_addr.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.member_name
     *
     * @return the value of sys_addr.member_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.member_name
     *
     * @param memberName the value for sys_addr.member_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.member_tel
     *
     * @return the value of sys_addr.member_tel
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberTel() {
        return memberTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.member_tel
     *
     * @param memberTel the value for sys_addr.member_tel
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberTel(String memberTel) {
        this.memberTel = memberTel == null ? null : memberTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_addr.addr_code
     *
     * @return the value of sys_addr.addr_code
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getAddrCode() {
        return addrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_addr.addr_code
     *
     * @param addrCode the value for sys_addr.addr_code
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setAddrCode(Integer addrCode) {
        this.addrCode = addrCode;
    }
}