package com.briup.sports.bean;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_course.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_course.course_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_course.course_price
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer coursePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_course.course_desc
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String courseDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_course.calorie_min
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double calorieMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_course.course_img
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String courseImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_course.course_id
     *
     * @return the value of sys_course.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_course.course_id
     *
     * @param courseId the value for sys_course.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_course.course_name
     *
     * @return the value of sys_course.course_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_course.course_name
     *
     * @param courseName the value for sys_course.course_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_course.course_price
     *
     * @return the value of sys_course.course_price
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_course.course_price
     *
     * @param coursePrice the value for sys_course.course_price
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCoursePrice(Integer coursePrice) {
        this.coursePrice = coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_course.course_desc
     *
     * @return the value of sys_course.course_desc
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getCourseDesc() {
        return courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_course.course_desc
     *
     * @param courseDesc the value for sys_course.course_desc
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc == null ? null : courseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_course.calorie_min
     *
     * @return the value of sys_course.calorie_min
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getCalorieMin() {
        return calorieMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_course.calorie_min
     *
     * @param calorieMin the value for sys_course.calorie_min
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCalorieMin(Double calorieMin) {
        this.calorieMin = calorieMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_course.course_img
     *
     * @return the value of sys_course.course_img
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getCourseImg() {
        return courseImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_course.course_img
     *
     * @param courseImg the value for sys_course.course_img
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCourseImg(String courseImg) {
        this.courseImg = courseImg == null ? null : courseImg.trim();
    }
}