package com.briup.sports.bean;

import java.util.Date;

public class ExerciseLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_log.log_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_log.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_log.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_log.total_cal
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double totalCal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exercise_log.date
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_log.log_id
     *
     * @return the value of exercise_log.log_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_log.log_id
     *
     * @param logId the value for exercise_log.log_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_log.member_id
     *
     * @return the value of exercise_log.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_log.member_id
     *
     * @param memberId the value for exercise_log.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_log.course_id
     *
     * @return the value of exercise_log.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_log.course_id
     *
     * @param courseId the value for exercise_log.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_log.total_cal
     *
     * @return the value of exercise_log.total_cal
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getTotalCal() {
        return totalCal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_log.total_cal
     *
     * @param totalCal the value for exercise_log.total_cal
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setTotalCal(Double totalCal) {
        this.totalCal = totalCal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exercise_log.date
     *
     * @return the value of exercise_log.date
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exercise_log.date
     *
     * @param date the value for exercise_log.date
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setDate(Date date) {
        this.date = date;
    }
}