package com.briup.sports.bean;

import java.util.ArrayList;
import java.util.List;

public class MemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public MemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Integer value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Integer value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Integer value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Integer> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNull() {
            addCriterion("member_name is null");
            return (Criteria) this;
        }

        public Criteria andMemberNameIsNotNull() {
            addCriterion("member_name is not null");
            return (Criteria) this;
        }

        public Criteria andMemberNameEqualTo(String value) {
            addCriterion("member_name =", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotEqualTo(String value) {
            addCriterion("member_name <>", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThan(String value) {
            addCriterion("member_name >", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
            addCriterion("member_name >=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThan(String value) {
            addCriterion("member_name <", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLessThanOrEqualTo(String value) {
            addCriterion("member_name <=", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameLike(String value) {
            addCriterion("member_name like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotLike(String value) {
            addCriterion("member_name not like", value, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameIn(List<String> values) {
            addCriterion("member_name in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotIn(List<String> values) {
            addCriterion("member_name not in", values, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameBetween(String value1, String value2) {
            addCriterion("member_name between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberNameNotBetween(String value1, String value2) {
            addCriterion("member_name not between", value1, value2, "memberName");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordIsNull() {
            addCriterion("member_password is null");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordIsNotNull() {
            addCriterion("member_password is not null");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordEqualTo(String value) {
            addCriterion("member_password =", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordNotEqualTo(String value) {
            addCriterion("member_password <>", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordGreaterThan(String value) {
            addCriterion("member_password >", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("member_password >=", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordLessThan(String value) {
            addCriterion("member_password <", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordLessThanOrEqualTo(String value) {
            addCriterion("member_password <=", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordLike(String value) {
            addCriterion("member_password like", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordNotLike(String value) {
            addCriterion("member_password not like", value, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordIn(List<String> values) {
            addCriterion("member_password in", values, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordNotIn(List<String> values) {
            addCriterion("member_password not in", values, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordBetween(String value1, String value2) {
            addCriterion("member_password between", value1, value2, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberPasswordNotBetween(String value1, String value2) {
            addCriterion("member_password not between", value1, value2, "memberPassword");
            return (Criteria) this;
        }

        public Criteria andMemberDescIsNull() {
            addCriterion("member_desc is null");
            return (Criteria) this;
        }

        public Criteria andMemberDescIsNotNull() {
            addCriterion("member_desc is not null");
            return (Criteria) this;
        }

        public Criteria andMemberDescEqualTo(String value) {
            addCriterion("member_desc =", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescNotEqualTo(String value) {
            addCriterion("member_desc <>", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescGreaterThan(String value) {
            addCriterion("member_desc >", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescGreaterThanOrEqualTo(String value) {
            addCriterion("member_desc >=", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescLessThan(String value) {
            addCriterion("member_desc <", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescLessThanOrEqualTo(String value) {
            addCriterion("member_desc <=", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescLike(String value) {
            addCriterion("member_desc like", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescNotLike(String value) {
            addCriterion("member_desc not like", value, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescIn(List<String> values) {
            addCriterion("member_desc in", values, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescNotIn(List<String> values) {
            addCriterion("member_desc not in", values, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescBetween(String value1, String value2) {
            addCriterion("member_desc between", value1, value2, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberDescNotBetween(String value1, String value2) {
            addCriterion("member_desc not between", value1, value2, "memberDesc");
            return (Criteria) this;
        }

        public Criteria andMemberEmailIsNull() {
            addCriterion("member_email is null");
            return (Criteria) this;
        }

        public Criteria andMemberEmailIsNotNull() {
            addCriterion("member_email is not null");
            return (Criteria) this;
        }

        public Criteria andMemberEmailEqualTo(String value) {
            addCriterion("member_email =", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailNotEqualTo(String value) {
            addCriterion("member_email <>", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailGreaterThan(String value) {
            addCriterion("member_email >", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailGreaterThanOrEqualTo(String value) {
            addCriterion("member_email >=", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailLessThan(String value) {
            addCriterion("member_email <", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailLessThanOrEqualTo(String value) {
            addCriterion("member_email <=", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailLike(String value) {
            addCriterion("member_email like", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailNotLike(String value) {
            addCriterion("member_email not like", value, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailIn(List<String> values) {
            addCriterion("member_email in", values, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailNotIn(List<String> values) {
            addCriterion("member_email not in", values, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailBetween(String value1, String value2) {
            addCriterion("member_email between", value1, value2, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberEmailNotBetween(String value1, String value2) {
            addCriterion("member_email not between", value1, value2, "memberEmail");
            return (Criteria) this;
        }

        public Criteria andMemberTelIsNull() {
            addCriterion("member_tel is null");
            return (Criteria) this;
        }

        public Criteria andMemberTelIsNotNull() {
            addCriterion("member_tel is not null");
            return (Criteria) this;
        }

        public Criteria andMemberTelEqualTo(String value) {
            addCriterion("member_tel =", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelNotEqualTo(String value) {
            addCriterion("member_tel <>", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelGreaterThan(String value) {
            addCriterion("member_tel >", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelGreaterThanOrEqualTo(String value) {
            addCriterion("member_tel >=", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelLessThan(String value) {
            addCriterion("member_tel <", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelLessThanOrEqualTo(String value) {
            addCriterion("member_tel <=", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelLike(String value) {
            addCriterion("member_tel like", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelNotLike(String value) {
            addCriterion("member_tel not like", value, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelIn(List<String> values) {
            addCriterion("member_tel in", values, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelNotIn(List<String> values) {
            addCriterion("member_tel not in", values, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelBetween(String value1, String value2) {
            addCriterion("member_tel between", value1, value2, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberTelNotBetween(String value1, String value2) {
            addCriterion("member_tel not between", value1, value2, "memberTel");
            return (Criteria) this;
        }

        public Criteria andMemberAddrIsNull() {
            addCriterion("member_addr is null");
            return (Criteria) this;
        }

        public Criteria andMemberAddrIsNotNull() {
            addCriterion("member_addr is not null");
            return (Criteria) this;
        }

        public Criteria andMemberAddrEqualTo(String value) {
            addCriterion("member_addr =", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotEqualTo(String value) {
            addCriterion("member_addr <>", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrGreaterThan(String value) {
            addCriterion("member_addr >", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrGreaterThanOrEqualTo(String value) {
            addCriterion("member_addr >=", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrLessThan(String value) {
            addCriterion("member_addr <", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrLessThanOrEqualTo(String value) {
            addCriterion("member_addr <=", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrLike(String value) {
            addCriterion("member_addr like", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotLike(String value) {
            addCriterion("member_addr not like", value, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrIn(List<String> values) {
            addCriterion("member_addr in", values, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotIn(List<String> values) {
            addCriterion("member_addr not in", values, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrBetween(String value1, String value2) {
            addCriterion("member_addr between", value1, value2, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAddrNotBetween(String value1, String value2) {
            addCriterion("member_addr not between", value1, value2, "memberAddr");
            return (Criteria) this;
        }

        public Criteria andMemberAgeIsNull() {
            addCriterion("member_age is null");
            return (Criteria) this;
        }

        public Criteria andMemberAgeIsNotNull() {
            addCriterion("member_age is not null");
            return (Criteria) this;
        }

        public Criteria andMemberAgeEqualTo(String value) {
            addCriterion("member_age =", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeNotEqualTo(String value) {
            addCriterion("member_age <>", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeGreaterThan(String value) {
            addCriterion("member_age >", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeGreaterThanOrEqualTo(String value) {
            addCriterion("member_age >=", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeLessThan(String value) {
            addCriterion("member_age <", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeLessThanOrEqualTo(String value) {
            addCriterion("member_age <=", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeLike(String value) {
            addCriterion("member_age like", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeNotLike(String value) {
            addCriterion("member_age not like", value, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeIn(List<String> values) {
            addCriterion("member_age in", values, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeNotIn(List<String> values) {
            addCriterion("member_age not in", values, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeBetween(String value1, String value2) {
            addCriterion("member_age between", value1, value2, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberAgeNotBetween(String value1, String value2) {
            addCriterion("member_age not between", value1, value2, "memberAge");
            return (Criteria) this;
        }

        public Criteria andMemberGenderIsNull() {
            addCriterion("member_gender is null");
            return (Criteria) this;
        }

        public Criteria andMemberGenderIsNotNull() {
            addCriterion("member_gender is not null");
            return (Criteria) this;
        }

        public Criteria andMemberGenderEqualTo(String value) {
            addCriterion("member_gender =", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderNotEqualTo(String value) {
            addCriterion("member_gender <>", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderGreaterThan(String value) {
            addCriterion("member_gender >", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderGreaterThanOrEqualTo(String value) {
            addCriterion("member_gender >=", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderLessThan(String value) {
            addCriterion("member_gender <", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderLessThanOrEqualTo(String value) {
            addCriterion("member_gender <=", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderLike(String value) {
            addCriterion("member_gender like", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderNotLike(String value) {
            addCriterion("member_gender not like", value, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderIn(List<String> values) {
            addCriterion("member_gender in", values, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderNotIn(List<String> values) {
            addCriterion("member_gender not in", values, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderBetween(String value1, String value2) {
            addCriterion("member_gender between", value1, value2, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberGenderNotBetween(String value1, String value2) {
            addCriterion("member_gender not between", value1, value2, "memberGender");
            return (Criteria) this;
        }

        public Criteria andMemberWeightIsNull() {
            addCriterion("member_weight is null");
            return (Criteria) this;
        }

        public Criteria andMemberWeightIsNotNull() {
            addCriterion("member_weight is not null");
            return (Criteria) this;
        }

        public Criteria andMemberWeightEqualTo(Double value) {
            addCriterion("member_weight =", value, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightNotEqualTo(Double value) {
            addCriterion("member_weight <>", value, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightGreaterThan(Double value) {
            addCriterion("member_weight >", value, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("member_weight >=", value, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightLessThan(Double value) {
            addCriterion("member_weight <", value, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightLessThanOrEqualTo(Double value) {
            addCriterion("member_weight <=", value, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightIn(List<Double> values) {
            addCriterion("member_weight in", values, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightNotIn(List<Double> values) {
            addCriterion("member_weight not in", values, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightBetween(Double value1, Double value2) {
            addCriterion("member_weight between", value1, value2, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberWeightNotBetween(Double value1, Double value2) {
            addCriterion("member_weight not between", value1, value2, "memberWeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightIsNull() {
            addCriterion("member_height is null");
            return (Criteria) this;
        }

        public Criteria andMemberHeightIsNotNull() {
            addCriterion("member_height is not null");
            return (Criteria) this;
        }

        public Criteria andMemberHeightEqualTo(Double value) {
            addCriterion("member_height =", value, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightNotEqualTo(Double value) {
            addCriterion("member_height <>", value, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightGreaterThan(Double value) {
            addCriterion("member_height >", value, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("member_height >=", value, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightLessThan(Double value) {
            addCriterion("member_height <", value, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightLessThanOrEqualTo(Double value) {
            addCriterion("member_height <=", value, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightIn(List<Double> values) {
            addCriterion("member_height in", values, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightNotIn(List<Double> values) {
            addCriterion("member_height not in", values, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightBetween(Double value1, Double value2) {
            addCriterion("member_height between", value1, value2, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberHeightNotBetween(Double value1, Double value2) {
            addCriterion("member_height not between", value1, value2, "memberHeight");
            return (Criteria) this;
        }

        public Criteria andMemberGoalIsNull() {
            addCriterion("member_goal is null");
            return (Criteria) this;
        }

        public Criteria andMemberGoalIsNotNull() {
            addCriterion("member_goal is not null");
            return (Criteria) this;
        }

        public Criteria andMemberGoalEqualTo(Double value) {
            addCriterion("member_goal =", value, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalNotEqualTo(Double value) {
            addCriterion("member_goal <>", value, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalGreaterThan(Double value) {
            addCriterion("member_goal >", value, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalGreaterThanOrEqualTo(Double value) {
            addCriterion("member_goal >=", value, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalLessThan(Double value) {
            addCriterion("member_goal <", value, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalLessThanOrEqualTo(Double value) {
            addCriterion("member_goal <=", value, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalIn(List<Double> values) {
            addCriterion("member_goal in", values, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalNotIn(List<Double> values) {
            addCriterion("member_goal not in", values, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalBetween(Double value1, Double value2) {
            addCriterion("member_goal between", value1, value2, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberGoalNotBetween(Double value1, Double value2) {
            addCriterion("member_goal not between", value1, value2, "memberGoal");
            return (Criteria) this;
        }

        public Criteria andMemberFlagIsNull() {
            addCriterion("member_flag is null");
            return (Criteria) this;
        }

        public Criteria andMemberFlagIsNotNull() {
            addCriterion("member_flag is not null");
            return (Criteria) this;
        }

        public Criteria andMemberFlagEqualTo(Integer value) {
            addCriterion("member_flag =", value, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagNotEqualTo(Integer value) {
            addCriterion("member_flag <>", value, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagGreaterThan(Integer value) {
            addCriterion("member_flag >", value, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_flag >=", value, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagLessThan(Integer value) {
            addCriterion("member_flag <", value, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagLessThanOrEqualTo(Integer value) {
            addCriterion("member_flag <=", value, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagIn(List<Integer> values) {
            addCriterion("member_flag in", values, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagNotIn(List<Integer> values) {
            addCriterion("member_flag not in", values, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagBetween(Integer value1, Integer value2) {
            addCriterion("member_flag between", value1, value2, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andMemberFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("member_flag not between", value1, value2, "memberFlag");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Integer value) {
            addCriterion("role_id =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Integer value) {
            addCriterion("role_id <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Integer value) {
            addCriterion("role_id >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("role_id >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Integer value) {
            addCriterion("role_id <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
            addCriterion("role_id <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Integer> values) {
            addCriterion("role_id in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Integer> values) {
            addCriterion("role_id not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Integer value1, Integer value2) {
            addCriterion("role_id between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("role_id not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Integer value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Integer value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Integer value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Integer value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Integer> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Integer> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andMemberImgIsNull() {
            addCriterion("member_img is null");
            return (Criteria) this;
        }

        public Criteria andMemberImgIsNotNull() {
            addCriterion("member_img is not null");
            return (Criteria) this;
        }

        public Criteria andMemberImgEqualTo(String value) {
            addCriterion("member_img =", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgNotEqualTo(String value) {
            addCriterion("member_img <>", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgGreaterThan(String value) {
            addCriterion("member_img >", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgGreaterThanOrEqualTo(String value) {
            addCriterion("member_img >=", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgLessThan(String value) {
            addCriterion("member_img <", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgLessThanOrEqualTo(String value) {
            addCriterion("member_img <=", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgLike(String value) {
            addCriterion("member_img like", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgNotLike(String value) {
            addCriterion("member_img not like", value, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgIn(List<String> values) {
            addCriterion("member_img in", values, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgNotIn(List<String> values) {
            addCriterion("member_img not in", values, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgBetween(String value1, String value2) {
            addCriterion("member_img between", value1, value2, "memberImg");
            return (Criteria) this;
        }

        public Criteria andMemberImgNotBetween(String value1, String value2) {
            addCriterion("member_img not between", value1, value2, "memberImg");
            return (Criteria) this;
        }

        public Criteria andCoachAgeIsNull() {
            addCriterion("coach_age is null");
            return (Criteria) this;
        }

        public Criteria andCoachAgeIsNotNull() {
            addCriterion("coach_age is not null");
            return (Criteria) this;
        }

        public Criteria andCoachAgeEqualTo(Integer value) {
            addCriterion("coach_age =", value, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeNotEqualTo(Integer value) {
            addCriterion("coach_age <>", value, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeGreaterThan(Integer value) {
            addCriterion("coach_age >", value, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("coach_age >=", value, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeLessThan(Integer value) {
            addCriterion("coach_age <", value, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeLessThanOrEqualTo(Integer value) {
            addCriterion("coach_age <=", value, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeIn(List<Integer> values) {
            addCriterion("coach_age in", values, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeNotIn(List<Integer> values) {
            addCriterion("coach_age not in", values, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeBetween(Integer value1, Integer value2) {
            addCriterion("coach_age between", value1, value2, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("coach_age not between", value1, value2, "coachAge");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameIsNull() {
            addCriterion("coach_course_name is null");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameIsNotNull() {
            addCriterion("coach_course_name is not null");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameEqualTo(String value) {
            addCriterion("coach_course_name =", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameNotEqualTo(String value) {
            addCriterion("coach_course_name <>", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameGreaterThan(String value) {
            addCriterion("coach_course_name >", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameGreaterThanOrEqualTo(String value) {
            addCriterion("coach_course_name >=", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameLessThan(String value) {
            addCriterion("coach_course_name <", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameLessThanOrEqualTo(String value) {
            addCriterion("coach_course_name <=", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameLike(String value) {
            addCriterion("coach_course_name like", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameNotLike(String value) {
            addCriterion("coach_course_name not like", value, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameIn(List<String> values) {
            addCriterion("coach_course_name in", values, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameNotIn(List<String> values) {
            addCriterion("coach_course_name not in", values, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameBetween(String value1, String value2) {
            addCriterion("coach_course_name between", value1, value2, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseNameNotBetween(String value1, String value2) {
            addCriterion("coach_course_name not between", value1, value2, "coachCourseName");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdIsNull() {
            addCriterion("coach_course_id is null");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdIsNotNull() {
            addCriterion("coach_course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdEqualTo(Integer value) {
            addCriterion("coach_course_id =", value, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdNotEqualTo(Integer value) {
            addCriterion("coach_course_id <>", value, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdGreaterThan(Integer value) {
            addCriterion("coach_course_id >", value, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("coach_course_id >=", value, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdLessThan(Integer value) {
            addCriterion("coach_course_id <", value, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdLessThanOrEqualTo(Integer value) {
            addCriterion("coach_course_id <=", value, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdIn(List<Integer> values) {
            addCriterion("coach_course_id in", values, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdNotIn(List<Integer> values) {
            addCriterion("coach_course_id not in", values, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdBetween(Integer value1, Integer value2) {
            addCriterion("coach_course_id between", value1, value2, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andCoachCourseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("coach_course_id not between", value1, value2, "coachCourseId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdIsNull() {
            addCriterion("default_addr_id is null");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdIsNotNull() {
            addCriterion("default_addr_id is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdEqualTo(Integer value) {
            addCriterion("default_addr_id =", value, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdNotEqualTo(Integer value) {
            addCriterion("default_addr_id <>", value, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdGreaterThan(Integer value) {
            addCriterion("default_addr_id >", value, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("default_addr_id >=", value, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdLessThan(Integer value) {
            addCriterion("default_addr_id <", value, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdLessThanOrEqualTo(Integer value) {
            addCriterion("default_addr_id <=", value, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdIn(List<Integer> values) {
            addCriterion("default_addr_id in", values, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdNotIn(List<Integer> values) {
            addCriterion("default_addr_id not in", values, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdBetween(Integer value1, Integer value2) {
            addCriterion("default_addr_id between", value1, value2, "defaultAddrId");
            return (Criteria) this;
        }

        public Criteria andDefaultAddrIdNotBetween(Integer value1, Integer value2) {
            addCriterion("default_addr_id not between", value1, value2, "defaultAddrId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_member
     *
     * @mbg.generated do_not_delete_during_merge Tue May 05 23:52:37 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_member
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}