package com.briup.sports.bean;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_password
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_desc
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_email
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_tel
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_age
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_gender
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double memberWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_height
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double memberHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_goal
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double memberGoal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_flag
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer memberFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.role_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.member_img
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String memberImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.coach_age
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer coachAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.coach_course_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String coachCourseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.coach_course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer coachCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_member.default_addr_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer defaultAddrId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_id
     *
     * @return the value of sys_member.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_id
     *
     * @param memberId the value for sys_member.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_name
     *
     * @return the value of sys_member.member_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_name
     *
     * @param memberName the value for sys_member.member_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_password
     *
     * @return the value of sys_member.member_password
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberPassword() {
        return memberPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_password
     *
     * @param memberPassword the value for sys_member.member_password
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberPassword(String memberPassword) {
        this.memberPassword = memberPassword == null ? null : memberPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_desc
     *
     * @return the value of sys_member.member_desc
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberDesc() {
        return memberDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_desc
     *
     * @param memberDesc the value for sys_member.member_desc
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberDesc(String memberDesc) {
        this.memberDesc = memberDesc == null ? null : memberDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_email
     *
     * @return the value of sys_member.member_email
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberEmail() {
        return memberEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_email
     *
     * @param memberEmail the value for sys_member.member_email
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail == null ? null : memberEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_tel
     *
     * @return the value of sys_member.member_tel
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberTel() {
        return memberTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_tel
     *
     * @param memberTel the value for sys_member.member_tel
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberTel(String memberTel) {
        this.memberTel = memberTel == null ? null : memberTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_addr
     *
     * @return the value of sys_member.member_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberAddr() {
        return memberAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_addr
     *
     * @param memberAddr the value for sys_member.member_addr
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberAddr(String memberAddr) {
        this.memberAddr = memberAddr == null ? null : memberAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_age
     *
     * @return the value of sys_member.member_age
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberAge() {
        return memberAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_age
     *
     * @param memberAge the value for sys_member.member_age
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberAge(String memberAge) {
        this.memberAge = memberAge == null ? null : memberAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_gender
     *
     * @return the value of sys_member.member_gender
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberGender() {
        return memberGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_gender
     *
     * @param memberGender the value for sys_member.member_gender
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberGender(String memberGender) {
        this.memberGender = memberGender == null ? null : memberGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_weight
     *
     * @return the value of sys_member.member_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getMemberWeight() {
        return memberWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_weight
     *
     * @param memberWeight the value for sys_member.member_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberWeight(Double memberWeight) {
        this.memberWeight = memberWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_height
     *
     * @return the value of sys_member.member_height
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getMemberHeight() {
        return memberHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_height
     *
     * @param memberHeight the value for sys_member.member_height
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberHeight(Double memberHeight) {
        this.memberHeight = memberHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_goal
     *
     * @return the value of sys_member.member_goal
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getMemberGoal() {
        return memberGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_goal
     *
     * @param memberGoal the value for sys_member.member_goal
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberGoal(Double memberGoal) {
        this.memberGoal = memberGoal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_flag
     *
     * @return the value of sys_member.member_flag
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getMemberFlag() {
        return memberFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_flag
     *
     * @param memberFlag the value for sys_member.member_flag
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberFlag(Integer memberFlag) {
        this.memberFlag = memberFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.role_id
     *
     * @return the value of sys_member.role_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.role_id
     *
     * @param roleId the value for sys_member.role_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.course_id
     *
     * @return the value of sys_member.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.course_id
     *
     * @param courseId the value for sys_member.course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.member_img
     *
     * @return the value of sys_member.member_img
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getMemberImg() {
        return memberImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.member_img
     *
     * @param memberImg the value for sys_member.member_img
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberImg(String memberImg) {
        this.memberImg = memberImg == null ? null : memberImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.coach_age
     *
     * @return the value of sys_member.coach_age
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getCoachAge() {
        return coachAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.coach_age
     *
     * @param coachAge the value for sys_member.coach_age
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCoachAge(Integer coachAge) {
        this.coachAge = coachAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.coach_course_name
     *
     * @return the value of sys_member.coach_course_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getCoachCourseName() {
        return coachCourseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.coach_course_name
     *
     * @param coachCourseName the value for sys_member.coach_course_name
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCoachCourseName(String coachCourseName) {
        this.coachCourseName = coachCourseName == null ? null : coachCourseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.coach_course_id
     *
     * @return the value of sys_member.coach_course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getCoachCourseId() {
        return coachCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.coach_course_id
     *
     * @param coachCourseId the value for sys_member.coach_course_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setCoachCourseId(Integer coachCourseId) {
        this.coachCourseId = coachCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_member.default_addr_id
     *
     * @return the value of sys_member.default_addr_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getDefaultAddrId() {
        return defaultAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_member.default_addr_id
     *
     * @param defaultAddrId the value for sys_member.default_addr_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setDefaultAddrId(Integer defaultAddrId) {
        this.defaultAddrId = defaultAddrId;
    }
}