package com.briup.sports.bean;

public class Qas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_qas.ids
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer ids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_qas.titles
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String titles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_qas.descs
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String descs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_qas.imgs
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String imgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_qas.ids
     *
     * @return the value of sys_qas.ids
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_qas.ids
     *
     * @param ids the value for sys_qas.ids
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setIds(Integer ids) {
        this.ids = ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_qas.titles
     *
     * @return the value of sys_qas.titles
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getTitles() {
        return titles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_qas.titles
     *
     * @param titles the value for sys_qas.titles
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setTitles(String titles) {
        this.titles = titles == null ? null : titles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_qas.descs
     *
     * @return the value of sys_qas.descs
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getDescs() {
        return descs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_qas.descs
     *
     * @param descs the value for sys_qas.descs
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_qas.imgs
     *
     * @return the value of sys_qas.imgs
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_qas.imgs
     *
     * @param imgs the value for sys_qas.imgs
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }
}