package com.briup.sports.bean;

public class Weight {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.weight_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String weightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.weight_num
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double weightNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.goal_distance
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double goalDistance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.weight_date
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private String weightDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.weight_change
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double weightChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_weight.member_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    private Double memberWeight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.weight_id
     *
     * @return the value of sys_weight.weight_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getWeightId() {
        return weightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.weight_id
     *
     * @param weightId the value for sys_weight.weight_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setWeightId(String weightId) {
        this.weightId = weightId == null ? null : weightId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.weight_num
     *
     * @return the value of sys_weight.weight_num
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getWeightNum() {
        return weightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.weight_num
     *
     * @param weightNum the value for sys_weight.weight_num
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setWeightNum(Double weightNum) {
        this.weightNum = weightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.goal_distance
     *
     * @return the value of sys_weight.goal_distance
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getGoalDistance() {
        return goalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.goal_distance
     *
     * @param goalDistance the value for sys_weight.goal_distance
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setGoalDistance(Double goalDistance) {
        this.goalDistance = goalDistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.weight_date
     *
     * @return the value of sys_weight.weight_date
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public String getWeightDate() {
        return weightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.weight_date
     *
     * @param weightDate the value for sys_weight.weight_date
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setWeightDate(String weightDate) {
        this.weightDate = weightDate == null ? null : weightDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.weight_change
     *
     * @return the value of sys_weight.weight_change
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getWeightChange() {
        return weightChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.weight_change
     *
     * @param weightChange the value for sys_weight.weight_change
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setWeightChange(Double weightChange) {
        this.weightChange = weightChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.member_id
     *
     * @return the value of sys_weight.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.member_id
     *
     * @param memberId the value for sys_weight.member_id
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_weight.member_weight
     *
     * @return the value of sys_weight.member_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public Double getMemberWeight() {
        return memberWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_weight.member_weight
     *
     * @param memberWeight the value for sys_weight.member_weight
     *
     * @mbg.generated Tue May 05 23:52:37 CST 2020
     */
    public void setMemberWeight(Double memberWeight) {
        this.memberWeight = memberWeight;
    }

    @Override
    public String toString() {
        return "Weight{" +
                "weightId='" + weightId + '\'' +
                ", weightNum=" + weightNum +
                ", goalDistance=" + goalDistance +
                ", weightDate='" + weightDate + '\'' +
                ", weightChange=" + weightChange +
                ", memberId=" + memberId +
                ", memberWeight=" + memberWeight +
                '}';
    }
}